# Generated by Django 3.0.2 on 2020-01-07 19:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='char',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='call',
            name='file',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
