# Generated by Django 3.0.2 on 2020-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callanalyzer', '0002_auto_20200108_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='call',
            name='char',
            field=models.CharField(max_length=9999),
        ),
    ]
