# Generated by Django 3.0.2 on 2020-01-08 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callanalyzer', '0003_auto_20200108_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
